spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ${ENVIRONMENT:dev}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${FAMILY_POSTGRES_HOST:localhost}:${POSTGRESDB_LOCAL_PORT:5432}/${DATABASE:copeuch}
    username: ${MS_USERNAME:postgres}
    password: ${MS_PASSWORD:asdf123}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-version: 1
    schemas: "public"
    locations: "classpath:db/migration"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    baseline-on-migrate: true
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-stacktrace: never

jwt:
  secret: "copeuch-challenge"
  expiration: 86400000